name: Who

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r src/css deploy/css
          cp -r src/img deploy/img
          cp -r src/json deploy/json
          cp src/index.html deploy/index.html
          cp -r dist/js deploy/js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
